name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Web Zip Package
        run: |
          zip -r web-app.zip . -x "*.git*"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-app-package
          path: web-app.zip
          
